STREET_VIEW_IMAGE_API_URL = 'https://maps.googleapis.com/maps/api/streetview'
DIRECTIONS_API_URL = 'https://maps.googleapis.com/maps/api/directions/json'

GMAPS_TURN_LEFT_MANEUVER = 'turn-left'
GMAPS_TURN_RIGHT_MANEUVER = 'turn-right'

GMAPS_KEY_DISTANCE = 'distance'
GMAPS_KEY_DURATION = 'duration'
GMAPS_KEY_VALUE = 'value'
GMAPS_KEY_START_ADDRESS = 'start_address'
GMAPS_KEY_END_ADDRESS = 'end_address'
GMAPS_KEY_START_LOCATION = 'start_location'
GMAPS_KEY_END_LOCATION = 'end_location'
GMAPS_KEY_STEPS = 'steps'
GMAPS_KEY_ROUTES = 'routes'
GMAPS_KEY_LEGS = 'legs'
GMAPS_KEY_LATITUDE = 'lat'
GMAPS_KEY_LONGITUDE = 'lng'
GMAPS_KEY_MANEUVER = 'maneuver'
GMAPS_KEY_STATUS = 'status'
GMAPS_KEY_HTML_INSTRUCTIONS = 'html_instructions'

GMAPS_PARAM_ORIGIN = 'origin'
GMAPS_PARAM_DESTINATION = 'destination'
GMAPS_PARAM_TRAVEL_MODE = 'mode'
GMAPS_PARAM_API_KEY = 'key'
GMAPS_PARAM_SIZE = 'size'
GMAPS_PARAM_HEADING = 'heading'
GMAPS_PARAM_LOCATION = 'location'

GMAPS_TRAVEL_MODE_BIKE = 'bicycling'
GMAPS_STATUS_OK = 'OK'

FINAL_DESTINATION_RIGHT = 'RIGHT'
FINAL_DESTINATION_LEFT = 'LEFT'
